// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dqttFxhDmHsNNwzjnwEK9t
// Component: lxP3S7dmzVk5g
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: a5Txphv_XF_FY/component
import Button from "../../Button"; // plasmic-import: _bcmwX0jFS3Tb/component
import ProductCard from "../../ProductCard"; // plasmic-import: mzQtI5MDDprSU/component
import Rating from "../../Rating"; // plasmic-import: 9yBHXD_zc5KHK/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: Y88CZPl9xMXEk/component
import Value from "../../Value"; // plasmic-import: 4npco0bsljb91/component
import Footer from "../../Footer"; // plasmic-import: 10gOmc-DVFuXz/component

import { useScreenVariants as useScreenVariantshjt93GPie8N1E } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hjt93GPie8N1e/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: dqttFxhDmHsNNwzjnwEK9t/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: lxP3S7dmzVk5g/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: 8C1PB62iWe1Ro/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: w6HFmaEyP7cBB/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: J79hQoCdT6BIU/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: BnFQdqqK-sKLg/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: PlqGbFUP1gfcG/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: hj7oYjqn1fe2n/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: G04lLSEOvZdf2/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: OV_4GL1q5al_9/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: sHbhl2qW7FY5i/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: IoDrIMBi-v7W9/icon

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  container42?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  container3?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  container4?: p.Flex<"div">;
  container?: p.Flex<"div">;
  emojiValueProps?: p.Flex<typeof EmojiValueProps>;
  columns?: p.Flex<"div">;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  container6?: p.Flex<"div">;
  container434?: p.Flex<"div">;
  container433?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomepageProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshjt93GPie8N1E()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section___4F396)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vGNz)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8JMWf)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection!"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jbpKm
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  className={classNames("__wab_instance", sty.button__lGuqr)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__eetLy)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  showEndIcon={true}
                  size={"large" as const}
                >
                  {"Shop"}
                </Button>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__jIvMg)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__yA4Uj)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w7Eu
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__si8Ew)}
                  colors={"link" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__z8NCt)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                >
                  {"See more"}
                </Button>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__qpves)}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe14.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__o3QkI)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hfUrL
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__opHZx
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__s4GxW)}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe15.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__k7NYf)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jTpnR
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qOhKz
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__tdR6D)}
                dollars={"64"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe16.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__ciNWz)}
                    rating={"two" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__adeCy
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eZWr
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___69JWl
                )}
                dollars={"99"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe17.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__mu94H)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__roOqS
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__puAs
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__zogjb)}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe18.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__bm2Jy)}
                    rating={"five" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jPyaJ
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nlh5Z
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__jCwbb)}
                dollars={"65"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe19.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__lTzP)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              />
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section___7Tdt8)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___56Mmr)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ocMee)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__s6HdQ)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zjV5S
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kroUh
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fpaE)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gPnwD
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <Button
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__kvj0F)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    size={"large" as const}
                  >
                    {"Shop sale"}
                  </Button>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__h5M7W)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xpvp0
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__vmouC)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__kU5Vi)}
                  icon={
                    <PlaneIcon
                      className={classNames(projectcss.all, sty.svg__wimD2)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fu8Wr
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vjCMk
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__wdfr3)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___0P1Vr
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__lQrv)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__sQ5Q3)}
                  icon={
                    <DocumentIcon
                      className={classNames(projectcss.all, sty.svg__x0MNl)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xGuot
                    )}
                  >
                    {"30-day guarantee"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__er5Uz
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__jl2X8)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__jM3Bj
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__fbI77)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__rwgPh)}
                  icon={
                    <LockIcon
                      className={classNames(projectcss.all, sty.svg__o5NZi)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qMwRd
                    )}
                  >
                    {"Secured payments"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jqUTp
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </p.Stack>
          </EmojiValueProps>

          <section className={classNames(projectcss.all, sty.section__u2DrB)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__azfUv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cYlBa
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___9AeSn
                      )}
                      colors={"link" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__vxSvo)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0DGY)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dK8A
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6J8Lf
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fUej
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m7Cp3
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lYtlr
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lSu6U
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lhux9
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ldap5
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__paRfH
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mPxWu
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__leU4E
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jTyzn
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i8W9B
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v1VEy
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cxOlY
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__p1Qw)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aBgJ8)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__morIi
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__cWcF)}
                  states={"active" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lmYcs
                    )}
                  >
                    {"All"}
                  </div>
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__k7NNh)}
                >
                  {"New"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__kx2T)}
                >
                  {"Womens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__liOpX)}
                >
                  {"Mens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__wglx1)}
                >
                  {"Kids"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__kmD1)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ymLmX
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___7QlOf)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xwCzN
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bpCq7
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f8Zp
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xuIJx
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vSmXv
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__srGdb
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0EhOd
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ziw4S
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yrfqP
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0Lwaj
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rgihA
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w3ElJ
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__egfA
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pFcAu
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uqmuR
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pj91H
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__my89C
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ySViw
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fup5M
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yNmP4
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cRoRf
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__a0A38
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5JLn
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zWmYh
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vDsYo
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x9FIn
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mRcjw
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__paZzo
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__csC7S
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lKwnp
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__g2L9N
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pO11P
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6G75I
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cJw0L
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vIr6
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3NC8
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__v5Pzl)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__wy6IK)}
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__cjStQ)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value__kJbuj)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__ftWq)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nc4Tz
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__onbBo
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section___8Sh03)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__mwa2)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___73Tg0
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__wSn1H)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__sYleE)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__eYxk7)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7ND0
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yqFLw
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__cmoqo)}
                    colors={"link" as const}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__u7P3L)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__wfFsY
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__paRHx)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__vCtHb)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__swQse)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xrNj
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3EbTi
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__a482W)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__kdYj6)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___0Y5A4
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__uVhnC)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___1Uxjm)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__dEbbW)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dmNxG
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bwLxR
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__aen3F)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__cy5GI)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__gaw9B
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__fdB5W)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__yxDlj)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__ptiJg)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8A7Vt
                    )}
                  >
                    {"We give back for every sale."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___63S
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__rSoUx)}
                    colors={"link" as const}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  emojiValueProps: typeof EmojiValueProps;
  columns: "div";
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
